[workspace]
resolver = "1"
members = [
    "./paios_booter"
]

[build]
target-dir = "."
bin-dir = "./"

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

